; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32-s3-devkitc-1-n16r8v
framework = arduino
lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit SSD1306
    bodmer/TFT_eSPI@^2.5.43

monitor_speed = 115200

build_unflags = -Os
build_flags =
    -O3
    -DBOARD_HAS_PSRAM
    -D ARDUINO_USB_MODE=1
    -DARDUINO_USB_CDC_ON_BOOT=0
    -D CONFIG_BT_ENABLED=0
    -D CONFIG_BLUEDROID_ENABLED=0
    -D CONFIG_ESP32_WIFI_SW_COEXIST_ENABLE=0
    -D CONFIG_ESP32_WIFI_ON=0
    -D CONFIG_ESP_WIFI_ENABLED=0
    -D USER_SETUP_LOADED=1
    -D ST7789_2_DRIVER=1
    -D TFT_WIDTH=240
    -D TFT_HEIGHT=240
    -D USE_HSPI_PORT=1
    -D TFT_MISO=13
    -D TFT_MOSI=11
    -D TFT_SCLK=12
    -D TFT_DC=9
    -D TFT_RST=14
    -D TOUCH_CS=-1
    -D TFT_BL=-1
    -D TFT_CS=10
    -D TFT_BACKLIGHT_ON=HIGH 
    -D TFT_RGB_ORDER=TFT_RGB
    -D LOAD_GLCD=1
    -D LOAD_FONT2=1
    -D TFT_INVERSION_ON=1
    -D USE_DMA=1
    -D SPI_FREQUENCY=80000000
    -D SPI_READ_FREQUENCY=20000000

board_build.partitions = partitions.csv
board_upload.flash_size = 16MB
board_build.flash_size = 16MB
build_type = release
board_build.f_flash = 80000000L
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi
board_build.flash_mode = qio
board_build.flash_freq = 80m
board_build.f_cpu = 240000000L
board_build.filesystem = littlefs